language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_b94deb0a83fd_key -iv $encrypted_b94deb0a83fd_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr package mcrt:publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: l49Eyu3lZdxFgZYeUEo+nVnLH9wn5p7vDSd1SHyz4JPGOsUCzdQ0Jp/KnnhioOkOFeC0ZaWbrKMO2nxk3/0MRQV4cqJMHwr/owdNr1smscMY3h+HUaPbrScXLgiFwYHb55hqeid8oj+DDPmx+MeJ1IgPilxWI8WwV0lJ/D2l87i0KodJDQHExVcJAGaJQsXFE8E12nGlpvKmAz6fatfZ9XbAKx8npaOpknUMmz1W2kXOsRnLmtce+gpfp8rZHmm2NYbxswZspXfIeaFX6MteafplX1CY4gWQ0WVfGCxkmSH8OI6I8+hDP9fidMje/8qcf3DWjanmRGidvHwf+mAajkaPKJcMXCl54L9kBqvM8g9ccefU5lx8yhtmAlPz2aVr6XCHf51x6cPvTP8Wtevvy68UdlbBPG+mVlHpRVihmDwJzQZZWJ7M8PHIebCmKIA4RIv2wRQ5cla/RK8q+YiABUd75yWDwRH/l06sBO0zujqyaD+XGpOBV/w5S8og3v7lZUBo7AWl5ObDOCNGGEfUgKLiHQHqm0Ry7xrODS7zrUb7+zVwLNncSCSPc7Ei3XgNmr06fYn9AYdo1oiywOcIh55DmfsIMhyqXYvbkfyKsWhkJ26GPAYhWiDL2T7Wq4LWkpfox12p7ski6YiHeUYQbfyHXnpckoJO8Zz9akCI7gs=
  - secure: WC+nMM5nl/xSkfhGS7lnN5M4TPduROmA84KlOC1qdBI0AVpaixcTLxNP735Zg+3jyJg5pv458oyaaIeii1A91dKsMiXSBmlIfOd5oYfKue2z3lqBa3Nnz7iOMB9k3Bt3VeXrohAI+14wNTFz4ZrE8Kh4c/js7WtJggNz8g5drZAH0aPa8mirkMBcEiYl7sKr++i679MVagzsDX2GcrR5oNYOFguK+jUJTZpBw382nYDonRDi9zzsGRxFRqyYCMBe+VufRwnuuo0u09jy4WeXWNC8ABHINu/R2rbiNmyOjKV/54VY07Afr+StS5jcSqk+me0MYeTRUKaQ5sQLAhj6JTwQE+RRSISOsgSaQzSzkCExNv8PwaL3UfekxKyVS0aJPVh+NGyoxcpZNVAdIImKc3e0rdFA4WJeOP32NkLU8c2vIXo3sYsTnWfLudaMcXcsb2E5pDC8vcCXjzOKLU2bpmA/KFW+NbI67QobGO+2UEQFCMvgm6nVxzoocNtuR/qjbVkX6H+OW/k/q+x+XMJrNXPW7iHVHXLMEf3/2RULNVXvz1rB9+xlcoztUuatp0+IG7M52MGdDNl/CmkEbPHi3WgxLEOuTaUetRpfQ2g3SpcPVwADrAqeKzkOUhuuIMW24JGbYexmp/RRKKSt2rSUh9fP/fEoP4tCjd/f1Xkzvlc=
  - secure: AH3AUCN7Xd9QiBOp25QNqCuZN/cnBjixI6lEl10CXwb/P6tHsix03CzZy8DgB3Ix4/qkU/9iPxykJPLczKduxarqpNvW1j8EE4k3YXu2Gv/ST2zME1115CiT7v4QMVlpMOzsLj5E4U7+UODSlFL92PLlJpA4m0y1ex5+Mi/0wnBkx29vgDpyNi01sSanZwk+YqLzomBNdhVJV+I5Sos2I+O1iNuyyR6n51hKiiptSb2Y1dtjTkO2vNwZjfS1zhEDi8Sf0rI+qs+7gFjtPHjiY2h/r29nKWMefn1o1ik0zDLDeWpB0RF5M7L/D/IT2tfz94DlHN+vnujyyri47FYpbl6Pwl4w8C9/ZH7ib5x7aG9VJ924FZyRYaRDurhIwvHlZ726pSXQu2idib3fL5/2LguYR22WaBbgltqc3Mmrg1hJ7GKl9F8w6vtl1K/Nr1Y6gdpDu8rsqko6AEm5p6UOVnZK56J7eibJJ4tCSzfvyqesatA3uTQc6pozTTRp6VKlT4QH/F6UFrN491VD0B4z2RZyrYwHq8RYQH0CiwGZHJ6iEIF6Ug4ftgsC9AtDPhoar5DxmIm/pA0bUlCoH+MO6NjdSwRCWZt/CJB/Mm/jfNcrjF2xB1T8CrI1NSLpXwVQ+wmE/DkWzMr9YDg8iFvv/ctBi27QJDMLpz0VFmUIJs4=
